- name: arithmetic
  items:
    - desc: Basic arithmetic (inequality)
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "asm1"
              - "x = 3"
          - - "asm2"
            - - "asm2"
              - "x > 1"
        goal: "x > 2"
    - desc: Intervals
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "xgt1"
              - "x > 1"
        goal: "\\between{x}{x+2}{2 \\cdot x}"
    - desc: Hyperbola
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x,y : \\Int"
        assumptions: []
        goal: "3 \\cdot x^3 + 17 \\2\\le x \\cdot y"

- name: sets
  items:
    - desc: Union and Subseteq
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z,w : \\set[\\Int]"
        assumptions: []
        goal: "x \\bunion y \\subseteq z \\binter w"
    - desc: Set Subtraction (Valid)
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z : \\set[\\Int]"
        assumptions: []
        goal: "x \\subseteq y \\bunion z \\equiv x \\setminus z \\subseteq y"
    - desc: Set Subtraction (Unknown)
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z : \\set[\\Int]"
        assumptions: []
        goal: "x \\subset y \\bunion z \\equiv x \\setminus z \\subset y"
    - desc: Type Error example
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x : \\set[ \\set[ \\Int ]]"
          - - "decl2"
            - "i : \\Int"
        assumptions:
          - - "asm1"
            - - "asm1"
              - "x = \\{ \\{ 7 \\} \\}"
        goal: "\\{ \\{ 3 \\}, x \\} \\subseteq \\{ \\{ 3, 7 \\} \\}\n\\2\\land \\qforall{j}{j \\le i}{i \\ge j-2}"

- name: functions
  items:
    - desc: Functions and Sets, with Exists
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\set [\\Int]"
        assumptions: []
        goal: "\\qexists{x}{x \\in \\dom.f}{f.x \\subseteq \\dom.f}"
    - desc: An Ill-definedness Example
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\Int"
          - - "decl2"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "f"
              - "f \\in \\qset{x}{x \\le 5}{x} \\tfun \\Int"
          - - "asm2"
            - - "xlt6"
              - "x \\le 6"
        goal: "f.x \\le 6"
    - desc: A Well-defined but Unknown example
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\Int"
          - - "decl2"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "f"
              - "f \\in \\qset{x}{x \\le 6}{x} \\tfun \\Int"
          - - "asm2"
            - - "xlt6"
              - "x \\le 6"
        goal: "f.x \\le 6"
