- name: arithmetic
  items:
    - desc: Basic arithmetic (inequality)
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "asm1"
              - "x = 3"
          - - "asm2"
            - - "asm2"
              - "x > 1"
        goal: "x > 2"
    - desc: Intervals
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "xgt1"
              - "x > 1"
        goal: "\\between{x}{x+2}{2 \\cdot x}"
    - desc: Hyperbola
      form:
        theories:
          - "arithmetic"
        declarations:
          - - "decl1"
            - "x,y : \\Int"
        assumptions: []
        goal: "3 \\cdot x^3 + 17 \\2\\le x \\cdot y"

- name: sets
  items:
    - desc: Union and Subseteq
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z,w : \\set[\\Int]"
        assumptions: []
        goal: "x \\bunion y \\subseteq z \\binter w"
    - desc: Set Subtraction (Valid)
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z : \\set[\\Int]"
        assumptions: []
        goal: "x \\subseteq y \\bunion z \\equiv x \\setminus z \\subseteq y"
    - desc: Set Subtraction (Unknown)
      form:
        theories:
          - "sets"
        declarations:
          - - "decl1"
            - "x,y,z : \\set[\\Int]"
        assumptions: []
        goal: "x \\subset y \\bunion z \\equiv x \\setminus z \\subset y"

- name: functions
  items:
    - desc: Functions and Sets, with Exists
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\set [\\Int]"
        assumptions: []
        goal: "\\qexists{x}{x \\in \\dom.f}{f.x \\subseteq \\dom.f}"
    - desc: An Ill-definedness Example
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\Int"
          - - "decl2"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "dom.f"
              - "\\dom.f = \\qset{y}{y \\le 5} {y}"
          - - "asm2"
            - - "xlt6"
              - "x \\le 6"
        goal: "f.x \\le 6"
    - desc: A Well-defined but Unknown example
      form:
        theories:
          - "functions"
          - "sets"
        declarations:
          - - "decl1"
            - "f : \\Int \\pfun \\Int"
          - - "decl2"
            - "x : \\Int"
        assumptions:
          - - "asm1"
            - - "dom.f"
              - "\\dom.f = \\qset{y}{y \\le 6} {y}"
          - - "asm2"
            - - "xlt6"
              - "x \\le 6"
        goal: "f.x \\le 6"
